language: node_js
node_js:
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
env:
  - NODE_ENV=test
services:
  - mongodb
  - rabbitmq
sudo: false
cache:
  directories:
    - node_modules
before_script:
  - npm install && npm install coveralls mocha-lcov-reporter --save-dev
script:
  - npm run test:travis
  - npm run build
notifications:
  email:
    on_success: never
    on_failure: always
